# Generated by Django 4.1.1 on 2022-11-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, error_messages={'invalid date': 'Введите дату в формате "Год-месяц-день"'}, null=True),
        ),
    ]
