# Generated by Django 4.1.1 on 2022-09-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(help_text='Это поле для имени знака Зодиака', max_length=20, unique=True, verbose_name='Знак зодиака')),
                ('sign_info', models.TextField(help_text='Это поле для информации о знакае Зодиака', max_length=300, verbose_name='Информация о знаке')),
            ],
        ),
    ]
