# Generated by Django 4.1.1 on 2022-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0002_sign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_image',
            field=models.ImageField(default='sign_images/libra.jpg', upload_to='sign_images/'),
        ),
    ]
