# Generated by Django 4.1.1 on 2022-09-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0008_alter_sign_sign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
