# Generated by Django 4.1.1 on 2022-09-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0011_alter_sign_sign_date_finish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='sign_date_finish',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='sign_date_start',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='sign_month',
        ),
    ]
