# Generated by Django 4.1.1 on 2022-09-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0013_sign_sign_date_finish_sign_sign_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='sign_date_finish',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='sign_date_start',
        ),
        migrations.AddField(
            model_name='sign',
            name='finish_date',
            field=models.IntegerField(default='31'),
        ),
        migrations.AddField(
            model_name='sign',
            name='month',
            field=models.CharField(default='февраль', max_length=20),
        ),
        migrations.AddField(
            model_name='sign',
            name='start_date',
            field=models.IntegerField(default='1'),
        ),
    ]
