# Generated by Django 4.1.1 on 2022-09-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0015_alter_sign_finish_date_alter_sign_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='finish_date',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='sign',
            name='start_date',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
