# Generated by Django 4.1.1 on 2022-09-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0018_alter_sign_finish_date_alter_sign_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='month',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='start_date',
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_finish_date',
            field=models.IntegerField(default=1, unique=True, verbose_name='дата2'),
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_month',
            field=models.CharField(default='февраль', max_length=20, unique=True, verbose_name='месяц'),
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_start_date',
            field=models.IntegerField(default=1, unique=True, verbose_name='дата'),
        ),
    ]
