# Generated by Django 4.1.1 on 2022-09-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0020_remove_sign_sign_finish_date_remove_sign_sign_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='sign_image',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='sign_info',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='sign_name',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='slug',
        ),
    ]
