# Generated by Django 4.1.1 on 2022-09-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0021_remove_sign_sign_image_remove_sign_sign_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='sign_finish_date',
            field=models.IntegerField(default=1, unique=True, verbose_name='дата2'),
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_image',
            field=models.ImageField(default='sign_images/libra.jpg', upload_to='sign_images'),
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_info',
            field=models.TextField(default='info', help_text='Это поле для информации о знакае Зодиака', max_length=300, verbose_name='Информация о знаке'),
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_month',
            field=models.CharField(default='февраль', max_length=20, unique=True, verbose_name='месяц'),
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_name',
            field=models.CharField(default='sign', help_text='Это поле для имени знака Зодиака', max_length=20, unique=True, verbose_name='Знак зодиака'),
        ),
        migrations.AddField(
            model_name='sign',
            name='sign_start_date',
            field=models.IntegerField(default=1, unique=True, verbose_name='дата'),
        ),
        migrations.AddField(
            model_name='sign',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
