# Generated by Django 4.1.1 on 2022-10-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0022_sign_sign_finish_date_sign_sign_image_sign_sign_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='sign_finish_date',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='sign_month',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='sign_start_date',
        ),
        migrations.AlterField(
            model_name='sign',
            name='sign_info',
            field=models.TextField(help_text='Это поле для информации о знакае Зодиака', max_length=300, verbose_name='Информация о знаке'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='sign_name',
            field=models.CharField(help_text='Это поле для имени знака Зодиака', max_length=20, unique=True, verbose_name='Знак зодиака'),
        ),
    ]
