# Generated by Django 4.1.1 on 2022-11-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0026_alter_sign_sign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='sign_horoscope_today',
            field=models.TextField(blank=True, default='Гороскоп еще не загрузился', help_text='Это поле для гороскопа', max_length=10000, null=True, verbose_name='Гороскоп на сегодня'),
        ),
    ]
